openapi: 3.1.0
info:
  title: BUSY Bar HTTP API
  description: HTTP API for BUSY Bar web server
  version: 27.8.0
  contact:
    name: tbd

security:
  - ApiKeyAuth: []
  - {}

paths:
  # {PATHS}

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Token

  schemas:
    SuccessResponse:
      type: object
      properties:
        result:
          type: string
          example: "OK"
          description: Success status message
      required:
        - result

    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
        error_code:
          type: string
          description: Error code
      required:
        - error
      example:
        error: "Invalid parameter"
        error_code: "invalid_parameter"

    # {SCHEMAS}

tags:
  # {TAGS}
